# Generated by Django 4.2.7 on 2024-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_api', '0001_initial'),
    ]

    operations = [
    ]
