# Generated by Django 4.2.7 on 2024-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_api', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrentemptable',
            name='badgeNo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='migrationRemark',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='migrationStatus',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
