# Generated by Django 4.2.7 on 2024-08-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_api', '0007_rename_attentionto_childrentemptable_attentionto1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreservicefamily',
            name='firstName',
            field=models.CharField(max_length=250),
        ),
    ]
