# Generated by Django 4.2.7 on 2024-08-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_api', '0008_alter_coreservicefamily_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='blockno',
            new_name='blocknoF',
        ),
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='building',
            new_name='blocknoM',
        ),
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='postalCode',
            new_name='buildingF',
        ),
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='street',
            new_name='buildingM',
        ),
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='transportOption',
            new_name='postalCodeF',
        ),
        migrations.RenameField(
            model_name='childrentemptable',
            old_name='unit',
            new_name='postalCodeM',
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='postalCodeRA1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='streetF',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='streetM',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='transportOptionF',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='transportOptionM',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='transportOptionRA1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='unitF',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childrentemptable',
            name='unitM',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
