# Generated by Django 4.2.2 on 2023-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTable',
            fields=[
                ('admissionId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('childId', models.CharField(max_length=250)),
                ('registrationDate', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('programId', models.CharField(max_length=250)),
                ('commencementDate', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='ChildTable',
            fields=[
                ('childId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('childNameENG', models.CharField(max_length=250)),
                ('childDOB', models.CharField(max_length=250)),
                ('childNRIC', models.CharField(max_length=250)),
                ('languageSpoken', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyTable',
            fields=[
                ('familyId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nRIC', models.DateField()),
                ('email', models.DateField()),
                ('occupation', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('relationship', models.CharField(max_length=250)),
                ('childId', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTable',
            fields=[
                ('programId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=250)),
                ('programDescription', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
    ]
