# Generated by Django 4.2.2 on 2023-08-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0004_healthchecktable_injurytable_surveysettings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveySettings',
            new_name='SurveySettingsTable',
        ),
        migrations.RenameField(
            model_name='surveysettingstable',
            old_name='surveyDescription',
            new_name='description',
        ),
    ]
