# Generated by Django 4.2.2 on 2023-08-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0004_healthchecktable_injurytable_surveysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySettingsTable',
            fields=[
                ('surveyId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('surveyTitle', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('questions', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.DeleteModel(
            name='SurveySettings',
        ),
    ]
