# Generated by Django 4.2.7 on 2023-11-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0006_pdffiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMediaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('hashtagValue', models.CharField(max_length=250)),
                ('fileURL', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
