# Generated by Django 4.2.7 on 2023-11-23 08:46

from django.db import migrations, models
import enjoey_api.storagebackend


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0008_alter_activitymediatable_hashtagvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymediatable',
            name='file',
            field=models.ImageField(storage=enjoey_api.storagebackend.ImageStorage(), upload_to=''),
        ),
    ]
