# Generated by Django 4.2.7 on 2023-11-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0009_alter_activitymediatable_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymediatable',
            name='fileURL',
        ),
    ]
