# Generated by Django 4.2.7 on 2023-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0011_paymenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAreaTagsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=250)),
                ('branchId', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=True)),
                ('enterBy', models.CharField(max_length=250)),
                ('isArchived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTagsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=250)),
                ('branchId', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=True)),
                ('enterBy', models.CharField(max_length=250)),
                ('isArchived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
    ]
