# Generated by Django 4.2.7 on 2023-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0012_activityareatagstable_activitytagstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('ageInterest', models.CharField(max_length=250)),
                ('branchName', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTimeSlotsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlotsId', models.CharField(max_length=250)),
                ('branchName', models.CharField(max_length=250)),
                ('ageInterest', models.CharField(max_length=250)),
                ('startTime', models.CharField(max_length=250)),
                ('endTime', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchId', models.CharField(max_length=250)),
                ('branchName', models.CharField(max_length=250)),
                ('branchLocation', models.CharField(max_length=250)),
                ('branchPrograms', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
    ]
