# Generated by Django 4.2.7 on 2023-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0012_activityareatagstable_activitytagstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTable',
            fields=[
                ('name', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('ageInterest', models.CharField(max_length=250)),
                ('branchId', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTimeSlotsTable',
            fields=[
                ('branchId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('ageInterest', models.CharField(max_length=250)),
                ('startTime', models.CharField(max_length=250)),
                ('endTime', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
    ]
