# Generated by Django 4.2.7 on 2023-12-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0013_appointmenttable_appointmenttimeslotstable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttable',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='appointmenttable',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='appointmenttable',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='appointmenttimeslotstable',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='appointmenttimeslotstable',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='appointmenttimeslotstable',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
