# Generated by Django 4.2.7 on 2023-12-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0014_rename_branchname_appointmenttable_branchid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonFormat', models.CharField()),
                ('htmlFormat', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
    ]
