# Generated by Django 4.2.7 on 2024-01-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0016_emailtemplatehtmltable_emailtemplatejsontable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestTable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
    ]
