# Generated by Django 4.2.7 on 2024-01-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0017_testtable1_testtable2_testtable3_testtable4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtable1',
            old_name='contents',
            new_name='firstData',
        ),
        migrations.RenameField(
            model_name='testtable1',
            old_name='data',
            new_name='secondData',
        ),
        migrations.RenameField(
            model_name='testtable2',
            old_name='contents',
            new_name='firstData',
        ),
        migrations.RenameField(
            model_name='testtable2',
            old_name='data',
            new_name='secondData',
        ),
        migrations.RenameField(
            model_name='testtable3',
            old_name='contents',
            new_name='firstData',
        ),
        migrations.RenameField(
            model_name='testtable3',
            old_name='data',
            new_name='secondData',
        ),
        migrations.RenameField(
            model_name='testtable4',
            old_name='contents',
            new_name='firstData',
        ),
        migrations.RenameField(
            model_name='testtable4',
            old_name='data',
            new_name='secondData',
        ),
    ]
