# Generated by Django 4.2.7 on 2024-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0020_coreservicechildren_coreservicechildrenallergies_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable1',
        ),
        migrations.DeleteModel(
            name='TestTable2',
        ),
        migrations.DeleteModel(
            name='TestTable3',
        ),
        migrations.DeleteModel(
            name='TestTable4',
        ),
        migrations.AlterField(
            model_name='coreservicechildrenallergies',
            name='haveMedicine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='coreservicefamily',
            name='isAllowPickup',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='haveMedicine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='isAllowPickup',
            field=models.BooleanField(),
        ),
    ]
