# Generated by Django 4.2.7 on 2024-02-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0024_alter_documentstable_documenturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentKeySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=250)),
                ('branchId', models.BigIntegerField(null=True)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('provider', models.CharField(max_length=250)),
                ('merchantId', models.CharField(max_length=250)),
                ('mode', models.CharField(choices=[('Test', 'Test'), ('Live', 'Live')], default='Test', max_length=15)),
                ('authKey1', models.CharField(max_length=255)),
                ('authKey2', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentstable',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='documentstable',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletedAt'),
        ),
        migrations.AlterField(
            model_name='documentstable',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updatedAt'),
        ),
    ]
