# Generated by Django 4.2.7 on 2024-04-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0028_publishsurveytable_useranswertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishsurveytable',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='publishsurveytable',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='publishsurveytable',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='useranswertable',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='useranswertable',
            old_name='deleted_at',
            new_name='deletedAt',
        ),
        migrations.RenameField(
            model_name='useranswertable',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
