# Generated by Django 4.2.7 on 2024-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0029_rename_created_at_publishsurveytable_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswertable',
            name='answer',
            field=models.CharField(),
        ),
    ]
