# Generated by Django 4.2.7 on 2024-06-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0030_alter_useranswertable_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('taxCategory', models.CharField(max_length=40)),
                ('taxCode', models.CharField(max_length=40)),
                ('taxRate', models.CharField(max_length=40)),
                ('startDate', models.CharField(max_length=40)),
                ('endDate', models.CharField(max_length=40, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
