# Generated by Django 4.2.7 on 2024-05-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0031_taxtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtable',
            name='endDate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
