# Generated by Django 4.2.7 on 2024-07-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0031_taxtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChildrenInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('foreignName', models.CharField(max_length=250)),
                ('studentID', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('birthDate', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('race', models.CharField(max_length=250)),
                ('citizenship', models.CharField(max_length=250)),
                ('religion', models.CharField(max_length=250)),
                ('motherTongue', models.CharField(max_length=250)),
                ('childOfStaff', models.CharField(max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('className', models.CharField(max_length=250)),
                ('transportationNo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestEmergencyContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrenId', models.CharField(max_length=250)),
                ('relationshipEC', models.CharField(max_length=250)),
                ('nameEC', models.CharField(max_length=250)),
                ('phoneEC', models.CharField(max_length=250)),
                ('emailEC', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestParentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrenId', models.CharField(max_length=250)),
                ('nameFamily', models.CharField(max_length=250)),
                ('phoneFamily', models.CharField(max_length=250)),
                ('emailFamily', models.CharField(max_length=250)),
                ('birthICFamily', models.CharField(max_length=250)),
                ('citizenshipFamily', models.CharField(max_length=250)),
                ('raceFamily', models.CharField(max_length=250)),
                ('occupationFamily', models.CharField(max_length=250)),
                ('relationshipFamily', models.CharField(max_length=250)),
                ('addressFamily', models.CharField(max_length=250)),
                ('stateFamily', models.CharField(max_length=250)),
                ('countryFamily', models.CharField(max_length=250)),
                ('postcodeFamily', models.CharField(max_length=250)),
                ('isAllowPickup', models.BooleanField()),
                ('mainContact', models.BooleanField()),
                ('emailInvoice', models.BooleanField()),
                ('emailCheckIn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSiblingsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrenID', models.CharField(max_length=250)),
                ('siblings', models.CharField(max_length=250)),
                ('relationship', models.CharField(max_length=250)),
            ],
        ),
    ]
