# Generated by Django 4.2.7 on 2024-07-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0032_testchildreninformation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestChildrenInformation',
        ),
        migrations.DeleteModel(
            name='TestEmergencyContactInformation',
        ),
        migrations.DeleteModel(
            name='TestParentInformation',
        ),
        migrations.DeleteModel(
            name='TestSiblingsInformation',
        ),
    ]
