# Generated by Django 4.2.7 on 2024-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0033_delete_testchildreninformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCalendarTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImg', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('startDate', models.CharField(max_length=40)),
                ('endDate', models.CharField(max_length=40)),
                ('startTime', models.CharField(max_length=40)),
                ('endTime', models.CharField(max_length=40)),
                ('receipt', models.CharField(max_length=40)),
                ('savedOptions', models.CharField(max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
