# Generated by Django 4.2.7 on 2024-08-13 02:17

from django.db import migrations, models
import enjoey_api.storagebackend


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0034_eventcalendartable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalendartable',
            name='allowOptions',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eventcalendartable',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='eventcalendartable',
            name='duration',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='eventcalendartable',
            name='inviteLink',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='eventcalendartable',
            name='time',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='coverImg',
            field=models.ImageField(null=True, storage=enjoey_api.storagebackend.ImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='endDate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='endTime',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='receipt',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='savedOptions',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='startDate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventcalendartable',
            name='startTime',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
