# Generated by Django 4.2.7 on 2024-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0036_alter_eventcalendartable_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcalendartable',
            name='savedOptions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
