import {BiAlignLeft} from 'react-icons/bi';
const routesConfig = [
  {
    id: 'app',
    title: 'Sample',
    messageId: 'landing.solutions',
    type: 'group',
    children: [
      {
        id: 'survey-editor',
        title: 'Survey Editor',
        messageId: 'Survey Editor',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SurveyEditor',
      },
      {
        id: 'survey-form',
        title: 'Survey Form',
        messageId: 'Survey Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SurveyForm',
      },
      {
        id: 'activities-form',
        title: 'Activities Form',
        messageId: 'Activities Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ActivitiesForm',
      },
      {
        id: 'menu-planning',
        title: 'Menu Planning',
        messageId: 'Menu Planning',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/MenuPlanning',
      },
      {
        id: 'sleep-check',
        title: 'Sleep Check',
        messageId: 'Sleep Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/SleepCheck',
      },
      {
        id: 'immunization',
        title: 'Immunization',
        messageId: 'Immunization',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/Immunization',
      },
      {
        id: 'health-check',
        title: 'Health Check',
        messageId: 'Health Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/HealthCheck',
      },
      {
        id: 'toilet-check',
        title: 'Toilet Check',
        messageId: 'Toilet Check',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ToiletCheck',
      },
      {
        id: 'injuries-form',
        title: 'Injuries Form',
        messageId: 'Injuries Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/InjuriesForm',
      },
      {
        id: 'injuries-form',
        title: 'Charges Form',
        messageId: 'Charges Form',
        type: 'item',
        icon: <BiAlignLeft />,
        url: '/sample/ChargesForm',
      },
    ],
  },
];
export default routesConfig;
